// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: aircount/v1/detection.proto

package aircountv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           string                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Rssi          int32                  `protobuf:"zigzag32,2,opt,name=rssi,proto3" json:"rssi,omitempty"`
	Channel       uint32                 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Frames        uint32                 `protobuf:"varint,4,opt,name=frames,proto3" json:"frames,omitempty"`
	RandomMac     bool                   `protobuf:"varint,5,opt,name=random_mac,json=randomMac,proto3" json:"random_mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_aircount_v1_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_aircount_v1_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_aircount_v1_detection_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Device) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *Device) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *Device) GetFrames() uint32 {
	if x != nil {
		return x.Frames
	}
	return 0
}

func (x *Device) GetRandomMac() bool {
	if x != nil {
		return x.RandomMac
	}
	return false
}

type DetectionBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Window        *durationpb.Duration   `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	UptimeMs      uint64                 `protobuf:"varint,4,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	Devices       []*Device              `protobuf:"bytes,5,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionBatch) Reset() {
	*x = DetectionBatch{}
	mi := &file_aircount_v1_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionBatch) ProtoMessage() {}

func (x *DetectionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_aircount_v1_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionBatch.ProtoReflect.Descriptor instead.
func (*DetectionBatch) Descriptor() ([]byte, []int) {
	return file_aircount_v1_detection_proto_rawDescGZIP(), []int{1}
}

func (x *DetectionBatch) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *DetectionBatch) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *DetectionBatch) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *DetectionBatch) GetUptimeMs() uint64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

func (x *DetectionBatch) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

var File_aircount_v1_detection_proto protoreflect.FileDescriptor

const file_aircount_v1_detection_proto_rawDesc = "" +
	"\n" +
	"\x1baircount/v1/detection.proto\x12\vaircount.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n" +
	"\x06Device\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\x12\x12\n" +
	"\x04rssi\x18\x02 \x01(\x11R\x04rssi\x12\x18\n" +
	"\achannel\x18\x03 \x01(\rR\achannel\x12\x16\n" +
	"\x06frames\x18\x04 \x01(\rR\x06frames\x12\x1d\n" +
	"\n" +
	"random_mac\x18\x05 \x01(\bR\trandomMac\"\xe9\x01\n" +
	"\x0eDetectionBatch\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12;\n" +
	"\vobserved_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x121\n" +
	"\x06window\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x06window\x12\x1b\n" +
	"\tuptime_ms\x18\x04 \x01(\x04R\buptimeMs\x12-\n" +
	"\adevices\x18\x05 \x03(\v2\x13.aircount.v1.DeviceR\adevicesB0Z.poltergeist/internal/pb/aircount/v1;aircountv1b\x06proto3"

var (
	file_aircount_v1_detection_proto_rawDescOnce sync.Once
	file_aircount_v1_detection_proto_rawDescData []byte
)

func file_aircount_v1_detection_proto_rawDescGZIP() []byte {
	file_aircount_v1_detection_proto_rawDescOnce.Do(func() {
		file_aircount_v1_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aircount_v1_detection_proto_rawDesc), len(file_aircount_v1_detection_proto_rawDesc)))
	})
	return file_aircount_v1_detection_proto_rawDescData
}

var file_aircount_v1_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aircount_v1_detection_proto_goTypes = []any{
	(*Device)(nil),                // 0: aircount.v1.Device
	(*DetectionBatch)(nil),        // 1: aircount.v1.DetectionBatch
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 3: google.protobuf.Duration
}
var file_aircount_v1_detection_proto_depIdxs = []int32{
	2, // 0: aircount.v1.DetectionBatch.observed_at:type_name -> google.protobuf.Timestamp
	3, // 1: aircount.v1.DetectionBatch.window:type_name -> google.protobuf.Duration
	0, // 2: aircount.v1.DetectionBatch.devices:type_name -> aircount.v1.Device
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_aircount_v1_detection_proto_init() }
func file_aircount_v1_detection_proto_init() {
	if File_aircount_v1_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aircount_v1_detection_proto_rawDesc), len(file_aircount_v1_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aircount_v1_detection_proto_goTypes,
		DependencyIndexes: file_aircount_v1_detection_proto_depIdxs,
		MessageInfos:      file_aircount_v1_detection_proto_msgTypes,
	}.Build()
	File_aircount_v1_detection_proto = out.File
	file_aircount_v1_detection_proto_goTypes = nil
	file_aircount_v1_detection_proto_depIdxs = nil
}
