// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: aircount/v1/presence.proto

package aircountv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresenceRF struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SensorId       string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	MotionDetected bool                   `protobuf:"varint,2,opt,name=motion_detected,json=motionDetected,proto3" json:"motion_detected,omitempty"`
	Score          float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	ObservedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Window         *durationpb.Duration   `protobuf:"bytes,5,opt,name=window,proto3" json:"window,omitempty"`
	Packets        uint32                 `protobuf:"varint,6,opt,name=packets,proto3" json:"packets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PresenceRF) Reset() {
	*x = PresenceRF{}
	mi := &file_aircount_v1_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceRF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceRF) ProtoMessage() {}

func (x *PresenceRF) ProtoReflect() protoreflect.Message {
	mi := &file_aircount_v1_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceRF.ProtoReflect.Descriptor instead.
func (*PresenceRF) Descriptor() ([]byte, []int) {
	return file_aircount_v1_presence_proto_rawDescGZIP(), []int{0}
}

func (x *PresenceRF) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *PresenceRF) GetMotionDetected() bool {
	if x != nil {
		return x.MotionDetected
	}
	return false
}

func (x *PresenceRF) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PresenceRF) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *PresenceRF) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *PresenceRF) GetPackets() uint32 {
	if x != nil {
		return x.Packets
	}
	return 0
}

var File_aircount_v1_presence_proto protoreflect.FileDescriptor

const file_aircount_v1_presence_proto_rawDesc = "" +
	"\n" +
	"\x1aaircount/v1/presence.proto\x12\vaircount.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n" +
	"\n" +
	"PresenceRF\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12'\n" +
	"\x0fmotion_detected\x18\x02 \x01(\bR\x0emotionDetected\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12;\n" +
	"\vobserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x121\n" +
	"\x06window\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x06window\x12\x18\n" +
	"\apackets\x18\x06 \x01(\rR\apacketsB0Z.poltergeist/internal/pb/aircount/v1;aircountv1b\x06proto3"

var (
	file_aircount_v1_presence_proto_rawDescOnce sync.Once
	file_aircount_v1_presence_proto_rawDescData []byte
)

func file_aircount_v1_presence_proto_rawDescGZIP() []byte {
	file_aircount_v1_presence_proto_rawDescOnce.Do(func() {
		file_aircount_v1_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aircount_v1_presence_proto_rawDesc), len(file_aircount_v1_presence_proto_rawDesc)))
	})
	return file_aircount_v1_presence_proto_rawDescData
}

var file_aircount_v1_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aircount_v1_presence_proto_goTypes = []any{
	(*PresenceRF)(nil),            // 0: aircount.v1.PresenceRF
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 2: google.protobuf.Duration
}
var file_aircount_v1_presence_proto_depIdxs = []int32{
	1, // 0: aircount.v1.PresenceRF.observed_at:type_name -> google.protobuf.Timestamp
	2, // 1: aircount.v1.PresenceRF.window:type_name -> google.protobuf.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_aircount_v1_presence_proto_init() }
func file_aircount_v1_presence_proto_init() {
	if File_aircount_v1_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aircount_v1_presence_proto_rawDesc), len(file_aircount_v1_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aircount_v1_presence_proto_goTypes,
		DependencyIndexes: file_aircount_v1_presence_proto_depIdxs,
		MessageInfos:      file_aircount_v1_presence_proto_msgTypes,
	}.Build()
	File_aircount_v1_presence_proto = out.File
	file_aircount_v1_presence_proto_goTypes = nil
	file_aircount_v1_presence_proto_depIdxs = nil
}
